import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Syne, Inter } from 'next/font/google'

const syne = Syne({
  subsets: ['latin'],
  variable: '--font-heading',
  weight: ['700', '800'],
})

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${syne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
